# Site/SEO settings
email: yunjea0312@naver.com
permalink: /:year/:month/:day/:title/
google_analytics: 

title: Yunjae's Blog
description: 
url: "https://leeyunjea.github.io"
baseurl: ""
twitter_username: 
default_img: "../../../_images/strawberry.jpg"

# Profile settings
name: yunjae
profile_img: 
profile: 
social:
github: "https://github.com/leeyunjea"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
